### ISSUE TITLE
Dedicated server on ARM 

### ISSUE THREAD

**Issue by njmartinez1234** [citra-emu/citra-multiplayer-dedicated#9]
Hello, I was trying to host a server for Super Smash Bros using a Raspberry Pi 3, but im having isssues with ARM architecture,
this is the error i get:

Unable to find image 'citraemu/citra-multiplayer-dedicated:latest' locally
latest: Pulling from citraemu/citra-multiplayer-dedicated
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.

any suggestions? 

thanks

**Comment by liushuyu** [comment]
I am very sorry, but we currently don't have an `armv7` (`aarch32`) version of the dedicated room image. We do have the `aarch64` (`armv8`) version of the image available.

If you are using a Raspberry Pi 3 Model B or B+, then chances are, your hardware is an `aarch64` board, but your operating system is 32-bit (due to some driver issues, the Raspberry Pi OS has a 32-bit userland).

Although it's possible to hack the codebase to build an `armv7` version of the image, it will be kind of problematic to provide and maintain such an image (Citra itself only supports 64-bit OS).

However, if you are feeling adventurous, another option is that you could install [Armbian](https://www.armbian.com/rpi4b/) onto your Raspberry Pi. Note that writing a new image will erase all your existing data, you need to back up everything before doing that. Also, a third-party OS may lack certain hardware features (like hardware-accelerated video decoding), you may want to think about it before installing it.

**Comment by njmartinez1234** [comment]
> I am very sorry, but we currently don't have an `armv7` (`aarch32`) version of the dedicated room image. We do have the `aarch64` (`armv8`) version of the image available.
> 
> If you are using a Raspberry Pi 3 Model B or B+, then chances are, your hardware is an `aarch64` board, but your operating system is 32-bit (due to some driver issues, the Raspberry Pi OS has a 32-bit only userland).
> 
> Although it's possible to hack the codebase to build an `armv7` version of the image, it will be kind of problematic to provide and maintain such an image (Citra itself only supports 64-bit OS).
> 
> However, if you are feeling adventurous, another option is that you could install [Armbian](https://www.armbian.com/rpi4b/) onto your Raspberry Pi. Note that writing a new image will erase all your existing data, you need to back up everything before doing that. Also, a third-party OS may lack certain hardware features (like hardware-accelerated video decoding), you may want to think about it before installing it.

Hello, thanks for your quick response. you are absolutely right, my RP OS is X86 bits version, I'll try reinstalling X64.

Saludos
